# Generated by Django 6.0.6 on 2026-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_category_image_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='fallback_stock',
            field=models.IntegerField(default=0),
        ),
    ]
